version: "3.9"

services:
  database:
    image: mysql:5.7
    restart: always
    env_file:
      - database.env
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data: {}
